#**Day 3: Practice Session**

Dataset: IMdb dataset

In [1]:
import pandas as pd

In [2]:
#Read the csv file into python
movies_df = pd.read_csv('/content/IMDB-Movie-Data.csv',index_col='Title')

In [24]:
movies_df.head(5)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [4]:
#the last 5 rows in the dataset
movies_df.tail()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [5]:
# general information about the dataset including dtypes, non-null values.etc
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Genre               1000 non-null   object
 2   Description         1000 non-null   object
 3   Director            1000 non-null   object
 4   Actors              1000 non-null   object
 5   Year                1000 non-null   int64
 6   Runtime (Minutes)   1000 non-null   int64
 7   Rating              1000 non-null   float64
 8   Votes               1000 non-null   int64
 9   Revenue (Millions)  872 non-null    float64
 10  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 126.0+ KB

In [6]:
movies_df.shape

(1000, 11)

In [7]:
movies_df.columns

Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [8]:
#know more abou the statistical info in each numerical column
movies_df.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

In [9]:
#to understand object-type columns:
movies_df.describe(include='object')

,Genre,Description,Director,Actors
count,1000,1000,1000,1000
unique,207,1000,644,996
top,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,Ridley Scott,"Jennifer Lawrence, Josh Hutcherson, Liam Hemsw..."
freq,50,1,8,2

In [10]:
movies_df['Genre'].describe()

count                        1000
unique                        207
top       Action,Adventure,Sci-Fi
freq                           50
Name: Genre, dtype: object

In [12]:
movies_df['Actors'].describe()

count                                                  1000
unique                                                  996
top       Jennifer Lawrence, Josh Hutcherson, Liam Hemsw...
freq                                                      2
Name: Actors, dtype: object

In [13]:
# To extract frequency of values in a column==> value_counts()
movies_df['Genre'].value_counts()

Genre
Action,Adventure,Sci-Fi    50
Drama                      48
Comedy,Drama,Romance       35
Comedy                     32
Drama,Romance              31
                           ..
Action,Comedy,Family        1
Action,Crime,Fantasy        1
Comedy,Mystery              1
Adventure,Comedy,Horror     1
Comedy,Family,Fantasy       1
Name: count, Length: 207, dtype: int64

To extract a column from the dataframe:

In [17]:
genre_col=movies_df['Genre']
type(genre_col)

pandas.core.series.Series

In [18]:
# to extract a column as a dataframe: you will need to pass a list of columns []
genre_col = movies_df[['Genre']]
type(genre_col)

pandas.core.frame.DataFrame

In [16]:
# since its a list, adding another column name is easy:
subset_df = movies_df[['Genre','Actors']]
subset_df.head(2)

,Genre,Actors
Title,,
Guardians of the Galaxy,"Action,Adventure,Sci-Fi","Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S..."
Prometheus,"Adventure,Mystery,Sci-Fi","Noomi Rapace, Logan Marshall-Green, Michael Fa..."

In [ ]:
# create a subset df with columns: Genre, 'Rating', 'Revenue (Millions) and display the first 13 values and last 9 values

Row-wise Manipulation:

1. ```.loc```  : locates a row by name
2. `.iloc`  : locates by numerical index

In [19]:
movies_df.loc['Guardians of the Galaxy']

Rank                                                                  1
Genre                                           Action,Adventure,Sci-Fi
Description           A group of intergalactic criminals are forced ...
Director                                                     James Gunn
Actors                Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Year                                                               2014
Runtime (Minutes)                                                   121
Rating                                                              8.1
Votes                                                            757074
Revenue (Millions)                                               333.13
Metascore                                                          76.0
Name: Guardians of the Galaxy, dtype: object

In [20]:
movies_df.loc['Avatar']

Rank                                                                 88
Genre                                          Action,Adventure,Fantasy
Description           A paraplegic marine dispatched to the moon Pan...
Director                                                  James Cameron
Actors                Sam Worthington, Zoe Saldana, Sigourney Weaver...
Year                                                               2009
Runtime (Minutes)                                                   162
Rating                                                              7.8
Votes                                                            935408
Revenue (Millions)                                               760.51
Metascore                                                          83.0
Name: Avatar, dtype: object

In [22]:
movies_df.iloc[87]  # iloc: locate by numerical index

Rank                                                                 88
Genre                                          Action,Adventure,Fantasy
Description           A paraplegic marine dispatched to the moon Pan...
Director                                                  James Cameron
Actors                Sam Worthington, Zoe Saldana, Sigourney Weaver...
Year                                                               2009
Runtime (Minutes)                                                   162
Rating                                                              7.8
Votes                                                            935408
Revenue (Millions)                                               760.51
Metascore                                                          83.0
Name: Avatar, dtype: object

In [26]:
movies_df.iloc[0:4]  #movies from index 0 upto 4(excluding)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

#Exercise:

1. Locate the row with details of movie 'Arrival'
2. Locate the row details of Row no 440 to 445

In [28]:
movies_df.loc['Arrival']

Rank                                                                 20
Genre                                              Drama,Mystery,Sci-Fi
Description           When twelve mysterious spacecraft appear aroun...
Director                                               Denis Villeneuve
Actors                Amy Adams, Jeremy Renner, Forest Whitaker,Mich...
Year                                                               2016
Runtime (Minutes)                                                   116
Rating                                                              8.0
Votes                                                            340798
Revenue (Millions)                                                100.5
Metascore                                                          81.0
Name: Arrival, dtype: object

In [29]:
movies_df.iloc[440:446]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Oz the Great and Powerful,441,"Adventure,Family,Fantasy",A frustrated circus magician from Kansas is tr...,Sam Raimi,"James Franco, Michelle Williams, Rachel Weisz,...",2013,130,6.3,181521,234.90,44.0
Brooklyn,442,"Drama,Romance","An Irish immigrant lands in 1950s Brooklyn, wh...",John Crowley,"Saoirse Ronan, Emory Cohen, Domhnall Gleeson,J...",2015,117,7.5,94977,38.32,87.0
Coraline,443,"Animation,Family,Fantasy",An adventurous girl finds another world that i...,Henry Selick,"Dakota Fanning, Teri Hatcher, John Hodgman, Je...",2009,100,7.7,156620,75.28,80.0
Blue Valentine,444,"Drama,Romance",The relationship of a contemporary married cou...,Derek Cianfrance,"Ryan Gosling, Michelle Williams, John Doman,Fa...",2010,112,7.4,151409,9.70,81.0
The Thinning,445,Thriller,"""The Thinning"" takes place in a post-apocalypt...",Michael J. Gallagher,"Logan Paul, Peyton List, Lia Marie Johnson,Cal...",2016,81,6.0,4531,NaN,31.0
Silent Hill,446,"Adventure,Horror,Mystery","A woman, Rose, goes in search for her adopted ...",Christophe Gans,"Radha Mitchell, Laurie Holden, Sean Bean,Debor...",2006,125,6.6,184152,46.98,NaN

If i want to display details of separate rows at once:

In [30]:
# to extarct info from rows 0, 15 and 991

movies_df.iloc[[0,15,991]]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
The Secret Life of Pets,16,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
Taare Zameen Par,992,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0

# To extract information based on conditions:

In [31]:
#print info of movies with rating greater than 8.5

#df_name[condition]     condition: df_name['Rating']>8.5
#df_name[df_name['Rating']>8.5]

movies_df[movies_df['Rating']>8.5]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Interstellar,37,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
The Dark Knight,55,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
Inception,81,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
Kimi no na wa,97,"Animation,Drama,Fantasy",Two strangers find themselves linked in a biza...,Makoto Shinkai,"Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...",2016,106,8.6,34110,4.68,79.0
Dangal,118,"Action,Biography,Drama",Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...",2016,161,8.8,48969,11.15,NaN
The Intouchables,250,"Biography,Comedy,Drama",After he becomes a quadriplegic from a paragli...,Olivier Nakache,"François Cluzet, Omar Sy, Anne Le Ny, Audrey F...",2011,112,8.6,557965,13.18,57.0

Multiple Conditions: |==OR      &==AND

In [32]:
# print movies where James Gunn is Director

# df_name[condition]    condition: df_name['Director']=='James Gunn'

movies_df[movies_df['Director']=='James Gunn']

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Slither,909,"Comedy,Horror,Sci-Fi","A small town is taken over by an alien plague,...",James Gunn,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
Super,938,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0

In [34]:
# List movies og James Gunn with greater than 7 as rating
# condition: Director='James Gunn'  & 'Rating'<7

#        [               (condition1)          &     (condition2)         ]
movies_df[(movies_df['Director']=='James Gunn')& (movies_df['Rating']>7)]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0

In [ ]:
# List movies between the years 2010 to 2013

In [ ]:
# List movies between the years 2011 to 2015 with rating > 8

In [ ]:
# List movies between 2008 to 2014 with rating >7 and revenue >250

In [35]:
# Calculate the average rating
avg_rating = movies_df['Rating'].mean()
avg_rating

6.723199999999999

In [36]:
# show max rating
max_rating = movies_df['Rating'].max()
max_rating

9.0

In [37]:
# show the movie details where rating = 9
movies_df[movies_df['Rating']==9]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
The Dark Knight,55,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0

In [38]:
# show max revenue
max_revenue = movies_df['Revenue (Millions)'].max()
max_revenue

936.63

In [40]:
# show movie with max revenue
movies_df[movies_df['Revenue (Millions)']==max_revenue]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Star Wars: Episode VII - The Force Awakens,51,"Action,Adventure,Fantasy",Three decades after the defeat of the Galactic...,J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac, Domhna...",2015,136,8.1,661608,936.63,81.0

## Group by Function:

In [41]:
# group movies by director and also calculate average rating of each director
movies_df.groupby('Director')['Rating'].mean()

Director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             7.00
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.04
Zackary Adler          5.10
Name: Rating, Length: 644, dtype: float64

In [42]:
#Display the top 5 directors with highest average rating
# for sorting:  ASCENDING: sort_values()    DESCENDING: sort_values(ascending=False)
#          groupby(directors)==find mean rating==sort them in descending==display first 5
movies_df.groupby('Director')['Rating'].mean().sort_values(ascending=False).head(5)

Director
Nitesh Tiwari        8.80
Christopher Nolan    8.68
Olivier Nakache      8.60
Makoto Shinkai       8.60
Aamir Khan           8.50
Name: Rating, dtype: float64

In [43]:
## Display highest avg revenue of the top 5 years
## Group Data : ('Year')
## condition : 'Revenue'.mean()
## sort : descending order ==  sort_values(Acending=False)
## Display: first 5 years == head()
movies_df.groupby('Year')['Revenue (Millions)'].mean().sort_values(ascending=False).head()

Year
2009    112.601277
2012    107.973281
2010    105.081579
2008     99.082745
2007     87.882245
Name: Revenue (Millions), dtype: float64

In [49]:
# Find movies with high rating >8 and low revenue <50
# cond1 : movies_df['Rating'] >8
# cond2 : movies_df['Revenue(millions)'<50]
movies_df[(movies_df['Rating']>8.7) & (movies_df['Revenue (Millions)']<50)]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Dangal,118,"Action,Biography,Drama",Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...",2016,161,8.8,48969,11.15,NaN

In [ ]:
# Which genre generated max avg.revenue . Print the top 10 genres

In [ ]:
# Arrange movies based on genres to display avg  runtime and avg revenue in each genre

# **What is Matplotlib?**
Matplotlib is a popular Python library for displaying data and creating static, animated, and interactive plots. This program lets you draw appealing and informative graphics like line plots, scatter plots, histograms, and bar charts.

Matplotlib is highly customizable and flexible, which makes it a preferred choice for data analysts and scientists working in fields such as finance, science, engineering, and social sciences.

* Matplotlib is an open-source drawing library that supports various drawing types
* You can generate plots, histograms, bar charts, and other types of charts with just a few lines of code
* It’s often used in web application servers, shells, and Python scripts

## **Getting Started With Pyplot**
Pyplot is a Matplotlib module that provides simple functions for adding plot elements, such as lines, images, text, etc. to the axes in the current figure.

## **Dataset:**

 For this class, we will use the Dow Jones Industrial Average (DJIA) index’s historical prices from 2024-03-22 to 2024-06-20 ([Click here](https://www.wsj.com/market-data/quotes/index/DJIA/historical-prices)). You can set the date range on the page and then click the “download a spreadsheet” button.

The Dow Jones Industrial Average, Dow Jones, or simply the Dow, is a stock market index of 30 prominent companies listed on stock exchanges in the United States. The DJIA is one of the oldest and most commonly followed equity indexes.